### ISSUE TITLE
拦截器

### ISSUE THREAD

**Issue by DestinyHunter** [megalojs/megalo-api#2]
应该支持拦截器.比较方便多地方用同样参数的方法.

**Comment by DestinyHunter** [comment]
每个都有当然更好了..不过获取设备信息之类的拦截器好像没啥用.但是像关于视图和请求的就有必要了像.request,upload, showModal .showtoast 之类的

**Comment by elcarim5efil** [comment]
showModal 的拦截器是想类似这么用？

```javascript
Megalo.showToast.use(({ message, duration = 1000 }) => {
       return {
          message: `wrap [${message}]`,
          duration,
       }
})
```

**Comment by elcarim5efil** [comment]
其实就是加 aop 模式，before，after。

**Comment by DestinyHunter** [comment]
嗯. 有这样的需求.before 传入token ,加上loading, 改变颜色什么的.一次就行.不然每次用的时候都需要传入重复的值

**Comment by geminate** [comment]
其实可以考虑写一个全局方法，调用的时候用自己的全局方法

**Comment by zhuping** [comment]
have supported request interceptors #12
