### ISSUE TITLE
请问一下微信小程序中如何引入 Proxy

### ISSUE THREAD

**Issue by cwxyz007** [megalojs/megalo-api#8]
翻看源码的时候，偶然发现 `wechat` 里面使用了 [`Proxy`](https://github.com/megalojs/megalo-api/blob/0d3bdb7157b28688fdebe55527f4b97798f7de95/platforms/wechat/index.js#L15)，由于没有发现有使用什么其他工具，所以有点好奇是怎么实现的

因为 `Proxy` 是不能被 polyfill 的 ([Babel Docs](https://babeljs.io/docs/en/learn/#proxies))，而且[微信小程序文档](https://developers.weixin.qq.com/miniprogram/dev/devtools/details.html#%E5%AE%A2%E6%88%B7%E7%AB%AFes6-api-%E6%94%AF%E6%8C%81%E6%83%85%E5%86%B5)给出的 `ES6` 的支持范围，如下图，只有 `IOS 10` 及以上支持，所以想问一下是怎么实现的？

![image](https://user-images.githubusercontent.com/14226737/53775657-5c3c1e00-3f2e-11e9-9803-3e28a196ca1d.png)

```js
Megalo = new Proxy(Megalo, {
  get(target, key) {
    if (key in target) {
      return target[key];
    } else {
      console.warn(`微信小程序暂不支持 wx.${key.toString()}`);
      return target[key] = () => {};
    }
  }
});
```

**Comment by zhuping** [comment]
感谢指出，先前没注意到微信小程序下 `proxy` 的兼容性

**Comment by jiunacaikang** [comment]
> 感谢指出，先前没注意到微信小程序下 `proxy` 的兼容性

请问一下，iOS9中，Proxy不兼容问题，如何解决？
